export enum XsdDatatypes {
	xsdString = 'xsd:string',
	langString = 'rdf:langString',
	xsdBoolean = 'xsd:boolean',
	decimal = 'xsd:decimal',
	float = 'xsd:float',
	double = 'xsd:double',
	duration = 'xsd:duration',
	dateTime = 'xsd:dateTime',
	dateTimeStamp = 'xsd:dateTimeStamp',
	time = 'xsd:time',
	date = 'xsd:date',
	gYearMonth = 'xsd:gYearMonth',
	gYear = 'xsd:gYear',
	gMonthDay = 'xsd:gMonthDay',
	gDay = 'xsd:gDay',
	gMonth = 'xsd:gMonth',
	hexBinary = 'xsd:hexBinary',
	base64Binary = 'xsd:base64Binary',
	anyURI = 'xsd:anyURI',
	QName = 'xsd:QName',
	normalizedString = 'xsd:normalizedString',
	token = 'xsd:token',
	language = 'xsd:language',
	name_ = 'xsd:name',
	NCName = 'xsd:NCName',
	NMTOKEN = 'xsd:NMTOKEN',
	ID = 'xsd:ID',
	IDREF = 'xsd:IDREF',
	integer = 'xsd:integer',
	nonPositiveInteger = 'xsd:nonPositiveInteger',
	negativeInteger = 'xsd:negativeInteger',
	long = 'xsd:long',
	int = 'xsd:int',
	short = 'xsd:short',
	byte = 'xsd:byte',
	nonNegativeInteger = 'xsd:nonNegativeInteger',
	unsignedLong = 'xsd:unsignedLong',
	unsignedInt = 'xsd:unsignedInt',
	unsignedShort = 'xsd:unsignedShort',
	unsignedByte = 'xsd:unsignedByte',
	positiveInteger = 'xsd:positiveInteger'
}

// Add static-like method via a merged namespace
export function xsdDatatypeFromString(value: string): XsdDatatypes | undefined {
	return Object.values(XsdDatatypes).find((v) => v === value);
}